#!/bin/bash

alias yt-best='pwsh ~/.local/bin/powershell/ytdl.ps1 best'
alias yt-sub='pwsh ~/.local/bin/powershell/ytdl.ps1 subtitle'
alias startship='eval "$(starship init bash)"'
alias dark-mode='gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark'

# Git shortcut
alias gss='git status --short'
alias gst='git status'

alias ga='git add'
alias gaa='git add --all'

alias gcmsg='git commit --message'
alias gcam='git commit --all --message'

alias gp='git push'
alias gd='git diff'
alias gc='git clone --recurse-submodules'
