#!/bin/bash

short_pwd() {
  local pwd=$(pwd)
  pwd=${pwd/#$HOME/\~}
  sed 's:\([^/]\)[^/]*/:\1/:g' <<<"$pwd"
}

short_pwd_v2() {
  max_len=40
  max_dir_len=10
  trailing_dir=2
  
  long_pwd=${PWD/$HOME/\~}
  IFS='/' read -ra array_pwd <<< "$long_pwd"
  
  declare -i max_char=$max_dir_len-1
  declare -i dir_end=${#array_pwd[@]}-$trailing_dir-1
  
  join () {
    local IFS="$1"
    shift
    echo "$*"
  }
  
  if [ "${#long_pwd}" -gt "$max_len" ]; then
    for i in "${!array_pwd[@]}"; do
      dir_name=${array_pwd[$i]}
      if [ "${#dir_name}" -gt "$max_dir_len" ]; then
        substring=${dir_name:0:max_char}
        substring+="…"
        array_pwd[$i]=$substring
      fi
    done
  fi
  
  long_pwd_2=$(join / "${array_pwd[@]}")
  
  if [ "${#long_pwd_2}" -gt "$max_len" ]; then
    for i in $(seq 0 $dir_end); do
      dir_name=${array_pwd[$i]}
      chars=${dir_name:0:1}
      if [ "$chars" == '.' ]; then
        chars=${dir_name:0:2}
      fi
      array_pwd[$i]=$chars
    done
  fi
  
  echo $(join / "${array_pwd[@]}")
}

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]$(short_pwd_v2)\[\033[00m\]\$ '
