format = """
[░▒▓](#9A348E)\
${custom.pwd}\
[█](#DA627D)\
$git_branch\
$git_state\
$git_status\
[█](#FCA17D)\
$c\
$elixir\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$nodejs\
$rust\
[█](#86BBD8)\
$docker_context\
[█](#06969A)\
$cmd_duration\
$character"""

## SETTINGS ===============================================================

right_format = "($conda)"
command_timeout = 5000       # Timeout for commands executed (milliseconds)
add_newline = false  

## PURPLE ================================================================

[custom.pwd]
when = true
style = "bg:#9A348E"
command = "short-pwd"
format = '[ $output ]($style)'

## PINK ===================================================================

[git_branch]
symbol = ""
style = "bg:#DA627D"
format = '[$branch]($style)'

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind$stashed) ]($style)"
style = "bg:#DA627D"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bg:#DA627D"

## ORANGE =================================================================

[c]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#F4B183"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:#F4B183"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#F4B183"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[kotlin]
symbol = "\ue634"
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

[package]
style = "bg:#F4B183"
format = '[($version) ]($style)'

[rust]
symbol = ""
style = "bg:#F4B183"
format = '[$symbol ($version) ]($style)'

## SKY ===================================================================

[conda]
symbol = " "
#style = "bg:#86BBD8"
format = '[ \($environment\) ]($style)'

## BLUE ==================================================================

[cmd_duration]
#style = "bg:#33658A"
style = "bg:#06969A"
format = '[神$duration ]($style)'

## START =================================================================

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
